modules/Antivirus/Metadefender.py
Adding module for OPSWAT Metadefender. (Cancelled the old PR since it was on the master branch)
=> Add OPSWAT Metadefender module

modules/Antivirus/MSEScan.py
I'm including the raw output in the JSON in case we get something that breaks the parsing. Sample output:
```json
{
"/mnt/fireeyeshare/multiscanner/samples/test.zip": {
"Antivirus": {
"Microsoft Security Essentials": {
"malicious": true,
"raw_output": "...",
"threats": [
{
"resources": [
{                "file": "X:\\samples\\test.zip->eicar.txt"              },
{                "containerfile": "X:\\samples\\test.zip"              }
],
"threat": "Virus:DOS/EICAR_Test_File"
},
{
"resources": [
{                "file": "X:\\samples\\test.zip->ZHE5locked.docm->word/vbaProject.bin"              },
{                "file": "X:\\samples\\test.zip->O06Dlocked.docm->word/vbaProject.bin"              },
{                "file": "X:\\samples\\test.zip->M9FRlocked.docm->word/vbaProject.bin" …
```
=> Add Microsoft Security Essentials module

docs/modules.md, modules/Detonation/VxStream.py, tests/test_sqlite_db.py
* Add docs for VxStream to docs/module.md
* Fix some timeout logic in the VxStream module
=> Moar documentation

modules/Antivirus/Metadefender.py, tests/module_tests/Metadefender/retrieval_responses/200_found_complete.json, tests/module_tests/Metadefender/retrieval_responses/200_found_incomplete.json, tests/module_tests/Metadefender/retrieval_responses/200_not_found.json, tests/module_tests/Metadefender/test_metadefender_module.py
* Update Metadefender module with better error checking and handling
* Add Metadefender module unit tests
* Add Metadefender API key as configuration parameter
=> Additional Metadefender Module Updates

setup.py
This will allow you to pip install multiscanner, giving you an entry point of `multiscanner`. I have no idea how well it works.
=> Create an entry_point for multiscanner

docs/modules.md, modules/Detonation/Cuckoo.py
After talking about #35, moved MAEC report to key within Cuckoo JSON report.
=> Add ability to retrieve MAEC reports as part of Cuckoo JSON report.

docs/modules.md
Some documentation for module.
=> Add flare-floss documentation

docs/modules.md, libs/office_meta.py, modules/Metadata/officemeta.py
Add officemeta module based on CRITS officemeta module [1]
[1] https://github.com/crits/crits_services/tree/master/office_meta_service
TODO:
- Figure out proper licenses for added files
- Additional testing for py2 and py3 compatibility
=> Add officemeta module

docs/modules.md, modules/Metadata/impfuzzy.py, requirements.txt
Add module to do fuzzy hashing of PE imports using pyimpfuzzy [1].
[1] http://blog.jpcert.or.jp/2016/05/classifying-mal-a988.html
=> Add impfuzzy module

modules/MachineLearning/MaliciousMacroBot.py, requirements.txt
MaliciousMacroBot is a machine learning classifier intended to perform triage on Office documents https://github.com/egaus/MaliciousMacroBot
=> Add module for MaliciousMacroBot

setup.py
Changed code in line 60 in setup.py from:
`'console_scripts': ['multiscanner=multiscanner.multiscanner:_main']`
to:
`'console_scripts': ['multiscanner=multiscanner:_main']`
=> Fixed system library installation issue in setup.py

docs/testing.md
This didn't really feel like it belonged in the main README, so added a new page for it?
=> Add testing docs

libs/pdfparser.py
=> Update pdfparser.py to latest version.

setup.cfg, setup.py, utils/nsrl_parse.py
Not sure how this made it through CI...
=> Resolve merge conflict

utils/api.py, web/static/css/styles.css, web/templates/analyses.html, web/templates/history.html
=> Clean up code for deleting tasks

utils/api.py, web/static/css/styles.css, web/templates/analyses.html, web/templates/history.html, web/templates/report.html
=> Add 'Delete' button to report page

multiscanner.py, setup.cfg, web/app.py, web/templates/about.html, web/templates/layout.html, web/templates/system-health.html
- about: currently placeholder; will contain Multiscanner version info and maybe plugin info
- system-health: currently placeholder; will contain kibana iframe
- task-queue: redirects to flower gui
=> Add new tab for system information

utils/stix2_generator/__init__.py
=> WIP: Update stix2.Indicator labels to more descriptive ones

multiscanner.py
=> Add the ability to include tags from the command line

docker_utils/web_config.ini, web/app.py
Config option changes need to be propagated to docker folder.
=> Fix bug when web config options not present

storage/elasticsearch_storage.py, utils/api.py, web/app.py, web/static/css/styles.css, web/templates/index.html, web/templates/report.html
=> Upload tags

multiscanner.py
If I fat-finger a filename, I'd like to know about it instead of MultiScanner silently doing nothing.
=> Give a warning if the given file(s) weren't found

utils/nsrl_parse.py
=> Fix NSRL out of memory bug

multiscanner/common/pdf_generator/__init__.py, multiscanner/common/stix2_generator/__init__.py, multiscanner/distributed/api.py, multiscanner/modules/Antivirus/AVGScan.py, multiscanner/modules/Antivirus/McAfeeScan.py, multiscanner/modules/Antivirus/VFindScan.py, multiscanner/modules/Metadata/TrID.py, multiscanner/modules/Metadata/UADScan.py, multiscanner/modules/Metadata/pdfinfo.py, multiscanner/storage/elasticsearch_storage.py
mainly escape regular expression sequences.
=> incorporate flake8 changes

multiscanner/web/templates/analyses.html, multiscanner/web/templates/history.html
Fixes a styling issue found in #165, but doesn't depend on that PR.
=> Center DataTables buttons on Analyses/History pgs

multiscanner/web/templates/analytics.html
Will need a way to convert SHA256 -> link to report page
=> Rollback ssdeep page until better solution

multiscanner/distributed/api.py, multiscanner/storage/sql_driver.py, multiscanner/web/templates/analytics.html
The web app can't do the conversion, so it still requires an extra AJAX request, but it will only make the request when a row is clicked on, and only for that row, rather than making a request for every row like it was before #169.
=> Add endpoint to go from SHA256 sample ID to most recent task ID

multiscanner/distributed/api.py, multiscanner/web/templates/analyses.html, multiscanner/web/templates/history.html
Fixes the checkbox overlapping with the Task ID by adding an additional column.
=> Fix minor multi-select styling issue

docs/use/use-analysis-mods.rst, multiscanner/utils/nsrl_parse.py
Should have done this for the release candidates
=> Merge master into release/2.0.0rc1
